# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_headers": "03_convert_files.ipynb",
         "parse_header_line": "03_convert_files.ipynb",
         "restore_header": "03_convert_files.ipynb",
         "read__write_from_sep_sv": "03_convert_files.ipynb",
         "run_subprocess": "04_generate_report.ipynb",
         "create_base_directories": "02_initalise_repository.ipynb",
         "directory_is_empty": "02_initalise_repository.ipynb",
         "parse_directory_date_to_datetime": "02_initalise_repository.ipynb",
         "datetime_to_timestamp": "02_initalise_repository.ipynb",
         "delete_files_in_repository_directory": "02_initalise_repository.ipynb",
         "copy_directory_to_directory": "02_initalise_repository.ipynb",
         "rename_all_files_in_directory_from_txt_to_csv": "02_initalise_repository.ipynb",
         "add_all_new_files_to_respository": "02_initalise_repository.ipynb",
         "commit_repository": "02_initalise_repository.ipynb",
         "branch_exists": "02_initalise_repository.ipynb",
         "create_branch": "02_initalise_repository.ipynb",
         "switch_to_branch": "02_initalise_repository.ipynb",
         "repository_exists": "02_initalise_repository.ipynb",
         "create_repository": "02_initalise_repository.ipynb",
         "add_directory_to_repository": "02_initalise_repository.ipynb",
         "copy_into_repository": "02_initalise_repository.ipynb",
         "write_from_sep_sv": "03_convert_files.ipynb",
         "restore_header_in_mem": "03_convert_files.ipynb",
         "convert_directory": "03_convert_files.ipynb",
         "convert_dirs": "03_convert_files.ipynb",
         "get_output_from_cmd": "04_generate_report.ipynb",
         "verbose": "04_generate_report.ipynb",
         "show_progress": "04_generate_report.ipynb",
         "GitRepositoryReader": "04_generate_report.ipynb",
         "parse_commitstr_to_datetime": "04_generate_report.ipynb",
         "copyfile_fullpath": "04_generate_report.ipynb",
         "mkdir_for_fullpath": "04_generate_report.ipynb",
         "remove_files_from_output_branch": "04_generate_report.ipynb",
         "remove_files_from_output": "04_generate_report.ipynb",
         "get_report_name_refs": "04_generate_report.ipynb",
         "make_output_directories": "04_generate_report.ipynb",
         "get_relative_path": "04_generate_report.ipynb",
         "copy_style_and_bootstrap": "04_generate_report.ipynb",
         "bootstrap_navbar": "04_generate_report.ipynb",
         "header": "04_generate_report.ipynb",
         "footer": "04_generate_report.ipynb",
         "page": "04_generate_report.ipynb",
         "diff2html_template": "04_generate_report.ipynb",
         "default_footer": "04_generate_report.ipynb",
         "generate_difference_report_page": "04_generate_report.ipynb",
         "BranchComparisonReport": "04_generate_report.ipynb",
         "FileChangeHistoryReportForBranch": "04_generate_report.ipynb"}

modules = ["csv_header_restore.py",
           "convert_to_csv.py",
           "initalise_repository.py",
           "convert_files.py",
           "generate_report.py"]

doc_url = "https://3ideas.github.io/config_tracker/"

git_url = "https://github.com/3ideas/config_tracker/tree/master/"

def custom_doc_links(name): return None
